<?php

	/**
	 * Autoload manifest
	 *
	 * Autogenerated by manifester.php on 2009-07-08 01:27:37
	 *
	 * @package Testify
	 * @version 0.7.0
	 * @since   1.0
	 */
	
	return array(
		'ArrayHasKeyConstraint'          => 'Testify/framework/constraints/ArrayConstraints.php',
		'ArrayHasValueConstraint'        => 'Testify/framework/constraints/ArrayConstraints.php',
		'Assert'                         => 'Testify/framework/Assert.php',
		'Autoloader'                     => 'Testify/util/Autoloader.php',
		'Cli'                            => 'Testify/util/cli.php',
		'CliSwitch'                      => 'Testify/util/cli.php',
		'CliSwitchCollection'            => 'Testify/util/cli.php',
		'CombinedTestResult'             => 'Testify/framework/result/CombinedTestResult.php',
		'ConsoleListener'                => 'Testify/framework/listeners/ConsoleListener.php',
		'ConsoleTestRunner'              => 'Testify/framework/ConsoleTestRunner.php',
		'Constraint'                     => 'Testify/framework/constraints/Constraint.php',
		'CoverageDriver'                 => 'Testify/framework/reporting/CoverageGraphs.php',
		'CoverageFilter'                 => 'Testify/framework/reporting/CoverageFilter.php',
		'CoveragePalette'                => 'Testify/framework/reporting/CoverageGraphs.php',
		'CoveragePieChart'               => 'Testify/framework/reporting/CoverageGraphs.php',
		'CoverageRenderer'               => 'Testify/framework/reporting/CoverageGraphs.php',
		'CoverageReporter'               => 'Testify/framework/reporting/CoverageReporter.php',
		'DefaultConstraint'              => 'Testify/framework/constraints/DefaultConstraint.php',
		'EmptyConstraint'                => 'Testify/framework/constraints/SimpleConstraints.php',
		'EqualConstraint'                => 'Testify/framework/constraints/EqualConstraint.php',
		'ErredTest'                      => 'Testify/framework/result/FailedTest.php',
		'ErredTestResult'                => 'Testify/framework/result/SingleTestResults.php',
		'FailedTest'                     => 'Testify/framework/result/FailedTest.php',
		'FailedTestResult'               => 'Testify/framework/result/SingleTestResults.php',
		'FalseConstraint'                => 'Testify/framework/constraints/SimpleConstraints.php',
		'GreaterThanConstraint'          => 'Testify/framework/constraints/MathConstraints.php',
		'GreaterThanOrEqualToConstraint' => 'Testify/framework/constraints/MathConstraints.php',
		'IdenticalConstraint'            => 'Testify/framework/constraints/IdenticalConstraint.php',
		'IgnoredTest'                    => 'Testify/framework/result/FailedTest.php',
		'IgnoredTestResult'              => 'Testify/framework/result/SingleTestResults.php',
		'InvalidOptionException'         => 'Testify/framework/exceptions/Exceptions.php',
		'InvocationExpectation'          => 'Testify/framework/mock/InvocationExpectation.php',
		'InvocationTracker'              => 'Testify/framework/mock/InvocationTracker.php',
		'IsDirectoryConstraint'          => 'Testify/framework/constraints/SimpleConstraints.php',
		'IsFileConstraint'               => 'Testify/framework/constraints/SimpleConstraints.php',
		'IssetConstraint'                => 'Testify/framework/constraints/SimpleConstraints.php',
		'LessThanConstraint'             => 'Testify/framework/constraints/MathConstraints.php',
		'LessThanOrEqualToConstraint'    => 'Testify/framework/constraints/MathConstraints.php',
		'MockHandler'                    => 'Testify/framework/mock/MockHandler.php',
		'MockInvocation'                 => 'Testify/framework/mock/MockInvocation.php',
		'MockObject'                     => 'Testify/framework/mock/MockObjectCreator.php',
		'MockObjectCreator'              => 'Testify/framework/mock/MockObjectCreator.php',
		'MockRegistry'                   => 'Testify/framework/mock/MockRegistry.php',
		'NotConstraint'                  => 'Testify/framework/constraints/NotConstraint.php',
		'NullConstraint'                 => 'Testify/framework/constraints/SimpleConstraints.php',
		'PassedTestResult'               => 'Testify/framework/result/SingleTestResults.php',
		'PhpFileIterator'                => 'Testify/util/PhpFileIterator.php',
		'Product'                        => 'Testify/util/Product.php',
		'RecursivePhpFileIterator'       => 'Testify/util/PhpFileIterator.php',
		'RecursiveTestIterator'          => 'Testify/util/RecursiveTestIterator.php',
		'RecursivelyCountable'           => 'Testify/framework/test/Testable.php',
		'SimpleConstraint'               => 'Testify/framework/constraints/SimpleConstraints.php',
		'SingleTestResult'               => 'Testify/framework/result/SingleTestResults.php',
		'TestAccumulator'                => 'Testify/util/TestAccumulator.php',
		'TestCase'                       => 'Testify/framework/test/TestCase.php',
		'TestFailure'                    => 'Testify/framework/result/FailedTest.php',
		'TestListener'                   => 'Testify/framework/listeners/TestListener.php',
		'TestMethod'                     => 'Testify/framework/test/TestMethod.php',
		'TestResult'                     => 'Testify/framework/result/TestResult.php',
		'TestRunner'                     => 'Testify/framework/BaseTestRunner.php',
		'TestSuite'                      => 'Testify/framework/test/TestSuite.php',
		'Testable'                       => 'Testify/framework/test/Testable.php',
		'TestifyException'               => 'Testify/framework/exceptions/Exceptions.php',
		'TrueConstraint'                 => 'Testify/framework/constraints/SimpleConstraints.php',
		'TypeConstraint'                 => 'Testify/framework/constraints/TypeConstraint.php',
		'Usage'                          => 'Testify/util/cli.php',
		'Util'                           => 'Testify/util/Util.php'
	);

?>