<?php

	/**
	 * Autoload manifest
	 *
	 * Autogenerated by manifester.php on 2009-06-27 18:01:26
	 *
	 * @package TUnit
	 * @version 0.4.0
	 * @since   0.4.0
	 */
	
	return array(
		'Assert'                   => 'TUnit/framework/Assert.php',
		'Autoloader'               => 'TUnit/util/Autoloader.php',
		'Cli'                      => 'TUnit/util/cli.php',
		'CliSwitch'                => 'TUnit/util/cli.php',
		'CliSwitchCollection'      => 'TUnit/util/cli.php',
		'CombinedTestResult'       => 'TUnit/framework/result/CombinedTestResult.php',
		'ConsoleListener'          => 'TUnit/framework/listeners/ConsoleListener.php',
		'ConsoleTestRunner'        => 'TUnit/framework/ConsoleTestRunner.php',
		'Constraint'               => 'TUnit/framework/constraints/Constraint.php',
		'CoverageFilter'           => 'TUnit/framework/reporting/CoverageFilter.php',
		'CoverageReporter'         => 'TUnit/framework/reporting/CoverageReporter.php',
		'DefaultConstraint'        => 'TUnit/framework/constraints/DefaultConstraint.php',
		'EmptyConstraint'          => 'TUnit/framework/constraints/SimpleConstraints.php',
		'EqualConstraint'          => 'TUnit/framework/constraints/EqualConstraint.php',
		'ErredTest'                => 'TUnit/framework/result/FailedTest.php',
		'ErredTestResult'          => 'TUnit/framework/result/SingleTestResults.php',
		'FailedTest'               => 'TUnit/framework/result/FailedTest.php',
		'FailedTestResult'         => 'TUnit/framework/result/SingleTestResults.php',
		'FalseConstraint'          => 'TUnit/framework/constraints/SimpleConstraints.php',
		'IdenticalConstraint'      => 'TUnit/framework/constraints/IdenticalConstraint.php',
		'IgnoredTest'              => 'TUnit/framework/result/FailedTest.php',
		'IgnoredTestResult'        => 'TUnit/framework/result/SingleTestResults.php',
		'InvalidOptionException'   => 'TUnit/framework/exceptions/Exceptions.php',
		'InvocationExpectation'    => 'TUnit/framework/mock/InvocationExpectation.php',
		'InvocationTracker'        => 'TUnit/framework/mock/InvocationTracker.php',
		'IssetConstraint'          => 'TUnit/framework/constraints/SimpleConstraints.php',
		'MockHandler'              => 'TUnit/framework/mock/MockHandler.php',
		'MockInvocation'           => 'TUnit/framework/mock/MockInvocation.php',
		'MockObject'               => 'TUnit/framework/mock/MockObjectCreator.php',
		'MockObjectCreator'        => 'TUnit/framework/mock/MockObjectCreator.php',
		'MockRegistry'             => 'TUnit/framework/mock/MockRegistry.php',
		'NotConstraint'            => 'TUnit/framework/constraints/NotConstraint.php',
		'NullConstraint'           => 'TUnit/framework/constraints/SimpleConstraints.php',
		'PassedTestResult'         => 'TUnit/framework/result/SingleTestResults.php',
		'PhpFileIterator'          => 'TUnit/util/PhpFileIterator.php',
		'Product'                  => 'TUnit/util/Product.php',
		'RecursivePhpFileIterator' => 'TUnit/util/PhpFileIterator.php',
		'RecursiveTestIterator'    => 'TUnit/util/RecursiveTestIterator.php',
		'RecursivelyCountable'     => 'TUnit/framework/test/Testable.php',
		'SimpleConstraint'         => 'TUnit/framework/constraints/SimpleConstraints.php',
		'SingleTestResult'         => 'TUnit/framework/result/SingleTestResults.php',
		'TUnitException'           => 'TUnit/framework/exceptions/Exceptions.php',
		'TestAccumulator'          => 'TUnit/util/TestAccumulator.php',
		'TestCase'                 => 'TUnit/framework/test/TestCase.php',
		'TestFailure'              => 'TUnit/framework/result/FailedTest.php',
		'TestListener'             => 'TUnit/framework/listeners/TestListener.php',
		'TestMethod'               => 'TUnit/framework/test/TestMethod.php',
		'TestResult'               => 'TUnit/framework/result/TestResult.php',
		'TestRunner'               => 'TUnit/framework/BaseTestRunner.php',
		'TestSuite'                => 'TUnit/framework/test/TestSuite.php',
		'Testable'                 => 'TUnit/framework/test/Testable.php',
		'TrueConstraint'           => 'TUnit/framework/constraints/SimpleConstraints.php',
		'Usage'                    => 'TUnit/util/cli.php',
		'Util'                     => 'TUnit/util/Util.php'
	);

?>