<?php

	/**
	 * Autoload manifest
	 *
	 * Autogenerated by manifester.php on 2009-06-13 12:48:53
	 *
	 * @package TUnit
	 * @version 0.1.0
	 * @since   0.1.0
	 */
	
	return array(
		'Assert'              => 'TUnit/framework/Assert.php',
		'Autoloader'          => 'TUnit/util/Autoloader.php',
		'Cli'                 => 'TUnit/util/cli.php',
		'CliSwitch'           => 'TUnit/util/cli.php',
		'CliSwitchCollection' => 'TUnit/util/cli.php',
		'CombinedTestResult'  => 'TUnit/framework/result/CombinedTestResult.php',
		'ConsoleListener'     => 'TUnit/framework/listeners/ConsoleListener.php',
		'ErredTest'           => 'TUnit/framework/FailedTest.php',
		'ErredTestResult'     => 'TUnit/framework/result/ErredTestResult.php',
		'FailedTest'          => 'TUnit/framework/FailedTest.php',
		'FailedTestResult'    => 'TUnit/framework/result/FailedTestResult.php',
		'IgnoredTest'         => 'TUnit/framework/FailedTest.php',
		'IgnoredTestResult'   => 'TUnit/framework/result/IgnoredTestResult.php',
		'PassedTestResult'    => 'TUnit/framework/result/PassedTestResult.php',
		'TestCase'            => 'TUnit/framework/TestCase.php',
		'TestFailure'         => 'TUnit/framework/FailedTest.php',
		'TestListener'        => 'TUnit/framework/TestListener.php',
		'TestMethod'          => 'TUnit/framework/TestMethod.php',
		'TestResult'          => 'TUnit/framework/result/TestResult.php',
		'TestRunner'          => 'TUnit/framework/TestRunner.php',
		'TestSuite'           => 'TUnit/framework/TestSuite.php',
		'Testable'            => 'TUnit/framework/Testable.php',
		'Usage'               => 'TUnit/util/cli.php'
	);

?>